apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance
  labels:
    app: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: salman
        image: salman8095/insuranceproject:v1
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: insurance
  ports:
    - port: 8081
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8081
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 31000
